(TeX-add-style-hook "book"
 (lambda ()
    (LaTeX-add-index-entries
     "GNU Free Documentation License"
     "Free Documentation License, GNU"
     "Elkner, Jeff"
     "Olin College"
     "Meyers, Chris"
     "Creative Commons"
     "contributors"
     "problem solving"
     "program"
     "running Python"
     "Python!running"
     "Python in a browser"
     "PythonAnywhere"
     "Python 2"
     "interpreter"
     "prompt"
     "Hello, World"
     "quotation mark"
     "print statement"
     "statement!print"
     "function"
     "print function"
     "operator!arithmetic"
     "arithmetic operator"
     "bitwise operator"
     "operator!bitwise"
     "value"
     "type"
     "string"
     "integer"
     "floating-point"
     "class"
     "string type"
     "type!str"
     "int type"
     "type!int"
     "float type"
     "type!float"
     "sequence"
     "formal language"
     "natural language"
     "language!formal"
     "language!natural"
     "syntax"
     "token"
     "structure"
     "parse"
     "ambiguity"
     "redundancy"
     "literalness"
     "poetry"
     "prose"
     "debugging"
     "bug"
     "debugging!emotional response"
     "emotional debugging"
     "high-level language"
     "low-level language"
     "portability"
     "interpret"
     "operator"
     "error message"
     "calculator"
     "running pace"
     "variable"
     "assignment statement"
     "statement!assignment"
     "state diagram"
     "diagram!state"
     "underscore character"
     "keyword"
     "expression"
     "evaluate"
     "statement"
     "execute"
     "interactive mode"
     "script"
     "script mode"
     "order of operations"
     "PEMDAS"
     "string!operation"
     "operator!string"
     "concatenation"
     "commutativity"
     "comment"
     "syntax error"
     "error!syntax"
     "runtime error"
     "error!runtime"
     "exception"
     "safe language"
     "language!safe"
     "semantic error"
     "error!semantic"
     "assignment"
     "operand"
     "semantics"
     "function call"
     "parentheses!argument in"
     "argument"
     "return value"
     "conversion!type"
     "type conversion"
     "int function"
     "function!int"
     "float function"
     "function!float"
     "str function"
     "function!str"
     "math function"
     "function, math"
     "module"
     "module object"
     "dot notation"
     "log function"
     "function!log"
     "sine function"
     "radian"
     "trigonometric function"
     "function, trigonometric"
     "pi"
     "sqrt function"
     "function!sqrt"
     "composition"
     "SyntaxError"
     "exception!SyntaxError"
     "function definition"
     "definition!function"
     "def keyword"
     "keyword!def"
     "parentheses!empty"
     "header"
     "body"
     "indentation"
     "colon"
     "ellipses"
     "function type"
     "type!function"
     "use before def"
     "flow of execution"
     "parameter"
     "function parameter"
     "function argument"
     "parentheses!parameters in"
     "programmer-defined function"
     "function!programmer defined"
     "local variable"
     "variable!local"
     "NameError"
     "exception!NameError"
     "stack diagram"
     "function frame"
     "frame"
     "diagram!stack"
     "main"
     "traceback"
     "fruitful function"
     "void function"
     "function, fruitful"
     "function, void"
     "None special value"
     "special value!None"
     "NoneType type"
     "type!NoneType"
     "function, reasons for"
     "experimental debugging"
     "debugging!experimental"
     "Holmes, Sherlock"
     "Doyle, Arthur Conan"
     "Linux"
     "import statement"
     "statement!import"
     "len function"
     "function!len"
     "function object"
     "object!function"
     "grid"
     "repetition"
     "for loop"
     "loop!for"
     "statement!for"
     "loop"
     "polygon function"
     "function!polygon"
     "circle function"
     "function!circle"
     "arc function"
     "function!arc"
     "encapsulation"
     "generalization"
     "keyword argument"
     "argument!keyword"
     "interface"
     "refactoring"
     "development plan!encapsulation and generalization"
     "docstring"
     "triple-quoted string"
     "string!triple-quoted"
     "multiline string"
     "string!multiline"
     "precondition"
     "postcondition"
     "method"
     "development plan"
     "flower"
     "pie"
     "alphabet"
     "turtle typewriter"
     "typewriter, turtle"
     "spiral"
     "Archimedian spiral"
     "floor division"
     "floating-point division"
     "division!floor"
     "division!floating-point"
     "modulus operator"
     "operator!modulus"
     "divisibility"
     "boolean expression"
     "expression!boolean"
     "logical operator"
     "operator!logical"
     "True special value"
     "False special value"
     "special value!True"
     "special value!False"
     "bool type"
     "type!bool"
     "relational operator"
     "operator!relational"
     "and operator"
     "or operator"
     "not operator"
     "operator!and"
     "operator!or"
     "operator!not"
     "conditional statement"
     "statement!conditional"
     "if statement"
     "statement!if"
     "conditional execution"
     "condition"
     "compound statement"
     "statement!compound"
     "pass statement"
     "statement!pass"
     "alternative execution"
     "else keyword"
     "keyword!else"
     "branch"
     "chained conditional"
     "conditional!chained"
     "elif keyword"
     "keyword!elif"
     "nested conditional"
     "conditional!nested"
     "recursion"
     "function!recursive"
     "return statement"
     "statement!return"
     "base case"
     "recursion!base case"
     "infinite recursion"
     "recursion!infinite"
     "exception!RuntimeError"
     "RuntimeError"
     "keyboard input"
     "input function"
     "function!input"
     "newline"
     "ValueError"
     "exception!ValueError"
     "whitespace"
     "exception!OverflowError"
     "OverflowError"
     "Fermat's Last Theorem"
     "triangle"
     "TurtleWorld"
     "Koch curve"
     "temporary variable"
     "variable!temporary"
     "dead code"
     "abs function"
     "function!abs"
     "compare function"
     "function!compare"
     "development plan!incremental"
     "testing!incremental development"
     "Pythagorean theorem"
     "testing!knowing the answer"
     "sqrt"
     "scaffolding"
     "hypotenuse"
     "function composition"
     "boolean function"
     "Turing complete language"
     "language!Turing complete"
     "Turing, Alan"
     "Turing Thesis"
     "vorpal"
     "circular definition"
     "definition!circular"
     "factorial function"
     "function!factorial"
     "recursive definition"
     "leap of faith"
     "testing!leap of faith"
     "fibonacci function"
     "function!fibonacci"
     "type checking"
     "error checking"
     "gamma function"
     "isinstance function"
     "function!isinstance"
     "guardian pattern"
     "pattern!guardian"
     "incremental development"
     "Ackermann function"
     "function!ack"
     "palindrome"
     "greatest common divisor (GCD)"
     "GCD (greatest common divisor)"
     "reassignment"
     "equality and assignment"
     "update"
     "variable!updating"
     "initialization (before update)"
     "increment"
     "decrement"
     "statement!while"
     "while loop"
     "loop!while"
     "iteration"
     "infinite loop"
     "loop!infinite"
     "Collatz conjecture"
     "break statement"
     "statement!break"
     "square root"
     "Newton's method"
     "epsilon"
     "algorithm"
     "addition with carrying"
     "carrying, addition with"
     "subtraction!with borrowing"
     "borrowing, subtraction with"
     "debugging!by bisection"
     "bisection, debugging by"
     "initialization!variable"
     "algorithm!square root"
     "eval function"
     "function!eval"
     "Ramanujan, Srinivasa"
     "character"
     "bracket operator"
     "operator!bracket"
     "index"
     "index!starting at zero"
     "zero, index
  starting at"
     "exception!TypeError"
     "TypeError"
     "exception!IndexError"
     "IndexError"
     "index!negative"
     "negative index"
     "traversal"
     "loop!traversal"
     "abecedarian"
     "McCloskey, Robert"
     "slice operator"
     "operator!slice"
     "index!slice"
     "string!slice"
     "slice!string"
     "copy!slice"
     "slice!copy"
     "mutability"
     "immutability"
     "string!immutable"
     "object"
     "item"
     "item assignment"
     "assignment!item"
     "find function"
     "function!find"
     "search pattern"
     "pattern!search"
     "counter"
     "counting and looping"
     "looping and counting"
     "looping!with strings"
     "string!method"
     "invocation"
     "optional argument"
     "argument!optional"
     "in operator"
     "operator!in"
     "boolean operator"
     "operator!boolean"
     "string!comparison"
     "comparison!string"
     "slice"
     "empty string"
     "string method"
     "method!string"
     "count method"
     "method!count"
     "step size"
     "letter rotation"
     "rotation, letter"
     "Moby Project"
     "crosswords"
     "open function"
     "function!open"
     "plain text"
     "text!plain"
     "object!file"
     "file object"
     "readline method"
     "method!readline"
     "strip method"
     "method!strip"
     "lipogram"
     "reduction to a
  previously solved problem"
     "development plan!reduction"
     "looping!with indices"
     "index!looping with"
     "reduction to a previously solved problem"
     "testing!is hard"
     "program testing"
     "special case"
     "testing!and absence of bugs"
     "Dijkstra, Edsger"
     "Car Talk"
     "Puzzler"
     "double letters"
     "odometer"
     "list"
     "type!list"
     "element"
     "nested list"
     "list!nested"
     "empty list"
     "list!empty"
     "list!element"
     "access"
     "zero, index starting at"
     "list!index"
     "list!membership"
     "membership!list"
     "list!traversal"
     "traversal!list"
     "item update"
     "update!item"
     "list!operation"
     "concatenation!list"
     "list!concatenation"
     "repetition!list"
     "list!repetition"
     "list!slice"
     "slice!list"
     "list!copy"
     "slice!update"
     "update!slice"
     "list!method"
     "method, list"
     "append method"
     "method!append"
     "extend method"
     "method!extend"
     "sort method"
     "method!sort"
     "void method"
     "method!void"
     "update operator"
     "operator!update"
     "assignment!augmented"
     "augmented assignment"
     "accumulator!sum"
     "reduce pattern"
     "pattern!reduce"
     "accumulator!list"
     "map pattern"
     "pattern!map"
     "filter pattern"
     "pattern!filter"
     "element deletion"
     "deletion, element of list"
     "pop method"
     "method!pop"
     "del operator"
     "operator!del"
     "remove method"
     "method!remove"
     "list!function"
     "function!list"
     "split method"
     "method!split"
     "delimiter"
     "join method"
     "method!join"
     "string!empty"
     "aliasing"
     "is operator"
     "operator!is"
     "equivalence"
     "identity"
     "reference!aliasing"
     "reference"
     "list!as argument"
     "argument!list"
     "aliasing!copying to avoid"
     "copy!to avoid aliasing"
     "sorted!function"
     "function!sorted"
     "accumulator"
     "equivalent"
     "identical"
     "cumulative sum"
     "anagram"
     "duplicate"
     "uniqueness"
     "birthday paradox"
     "random module"
     "module!random"
     "randint function"
     "function!randint"
     "method append"
     "time module"
     "module!time"
     "membership!bisection search"
     "bisection search"
     "search, bisection"
     "membership!binary search"
     "binary search"
     "search, binary"
     "bisect module"
     "module!bisect"
     "reverse word pair"
     "interlocking words"
     "dictionary"
     "type!dict"
     "key"
     "key-value pair"
     "dict function"
     "function!dict"
     "squiggly bracket"
     "bracket!squiggly"
     "exception!KeyError"
     "KeyError"
     "membership!dictionary"
     "values method"
     "method!values"
     "implementation"
     "histogram"
     "frequency"
     "get method"
     "method!get"
     "dictionary!looping with"
     "looping!with dictionaries"
     "dictionary!lookup"
     "dictionary!reverse lookup"
     "lookup, dictionary"
     "reverse lookup, dictionary"
     "search"
     "raise statement"
     "statement!raise"
     "exception!LookupError"
     "LookupError"
     "invert dictionary"
     "dictionary!invert"
     "singleton"
     "hash function"
     "hashable"
     "call graph"
     "memo"
     "global variable"
     "variable!global"
     "flag"
     "global statement"
     "statement!global"
     "declaration"
     "update!global variable"
     "global variable!update"
     "UnboundLocalError"
     "exception!UnboundLocalError"
     "sanity check"
     "consistency check"
     "pretty print"
     "pprint module"
     "module!pprint"
     "mapping"
     "item!dictionary"
     "hashtable"
     "lookup"
     "reverse lookup"
     "diagram!call graph"
     "set membership"
     "membership!set"
     "setdefault method"
     "method!setdefault"
     "rotation!letters"
     "homophone"
     "reducible word"
     "word, reducible"
     "tuple"
     "type!tuple"
     "parentheses!tuples in"
     "tuple!singleton"
     "tuple function"
     "function!tuple"
     "tuple!slice"
     "slice!tuple"
     "comparison!tuple"
     "tuple!comparison"
     "tuple!assignment"
     "assignment!tuple"
     "swap pattern"
     "pattern!swap"
     "email address"
     "value!tuple"
     "return value!tuple"
     "function, tuple as return value"
     "divmod"
     "tuple assignment"
     "max function"
     "function!max"
     "min function"
     "function!min"
     "variable-length argument tuple"
     "argument!variable-length tuple"
     "gather"
     "parameter!gather"
     "argument!gather"
     "scatter"
     "argument scatter"
     "sum function"
     "function!sum"
     "zip function"
     "function!zip"
     "iterator"
     "list!of tuples"
     "enumerate function"
     "function!enumerate"
     "object!enumerate"
     "enumerate object"
     "items method"
     "method!items"
     "dictionary!initialize"
     "zip function!use with dict"
     "update method"
     "method!update"
     "traverse!dictionary"
     "dictionary!traversal"
     "tuple!as key in dictionary"
     "tuple!in brackets"
     "sorted function"
     "reversed function"
     "function!reversed"
     "data structure"
     "shape error"
     "error!shape"
     "structshape module"
     "module!structshape"
     "zip object"
     "object!zip"
     "shape"
     "letter
  frequency"
     "frequency!letter"
     "anagram set"
     "set!anagram"
     "Scrabble"
     "bingo"
     "metathesis"
     "definition!recursive"
     "string module"
     "module!string"
     "replace method"
     "method!replace"
     "translate method"
     "method!translate"
     "Project Gutenberg"
     "word frequency"
     "frequency!word"
     "random number"
     "number, random"
     "deterministic"
     "pseudorandom"
     "random function"
     "function!random"
     "choice function"
     "function!choice"
     "histogram!random choice"
     "histogram!word frequencies"
     "Austin, Jane"
     "accumulator!histogram"
     "update!histogram"
     "optional parameter"
     "parameter!optional"
     "default value"
     "value!default"
     "override"
     "dictionary!subtraction"
     "subtraction!dictionary"
     "set"
     "type!set"
     "Markov analysis"
     "prefix"
     "suffix"
     "random text"
     "text!random"
     "mash-up"
     "benchmarking"
     "profile module"
     "module!profile"
     "typographical error"
     "random walk programming"
     "development plan!random walk programming"
     "rubber duck debugging"
     "debugging!rubber duck"
     "Zipf's law"
     "logarithm"
     "matplotlib"
     "file"
     "type!file"
     "persistence"
     "pickle module"
     "module!pickle"
     "file!reading and writing"
     "close method"
     "method!close"
     "format operator"
     "operator!format"
     "format string"
     "format sequence"
     "filename"
     "path"
     "directory"
     "folder"
     "os module"
     "module!os"
     "getcwd function"
     "function!getcwd"
     "working directory"
     "directory!working"
     "relative path"
     "path!relative"
     "absolute path"
     "path!absolute"
     "exists function"
     "function!exists"
     "walk, directory"
     "directory!walk"
     "exception!IOError"
     "IOError"
     "file!permission"
     "permission, file"
     "exception, catching"
     "try statement"
     "statement!try"
     "database"
     "dbm
  module"
     "module!dbm"
     "database object"
     "object!database"
     "update!database"
     "bytes object"
     "object!bytes"
     "dictionary methods!dbm module"
     "pickling"
     "shelve module"
     "module!shelve"
     "shell"
     "pipe"
     "ls (Unix command)"
     "Unix command!ls"
     "popen function"
     "function!popen"
     "read method"
     "method!read"
     "md5"
     "checksum"
     "module, writing"
     "word count"
     "object!module"
     "name built-in variable"
     "module!reload"
     "reload function"
     "function!reload"
     "repr function"
     "function!repr"
     "string representation"
     "end of line character"
     "text file"
     "catch"
     "pipe object"
     "object!pipe"
     "MP3"
     "MD5 algorithm"
     "algorithm!MD5"
     "md5sum"
     "diff"
     "object-oriented programming"
     "programmer-defined type"
     "type!programmer-defined"
     "point, mathematical"
     "representation"
     "object!class"
     "class definition"
     "definition!class"
     "Point class"
     "class!Point"
     "class object"
     "instance"
     "instantiation"
     "hexadecimal"
     "instance attribute"
     "attribute!instance"
     "object diagram"
     "diagram!object"
     "instance!as argument"
     "Rectangle class"
     "class!Rectangle"
     "embedded object"
     "object!embedded"
     "instance!as return value"
     "object!mutable"
     "copying objects"
     "object!copying"
     "copy module"
     "module!copy"
     "embedded object!copying"
     "shallow copy"
     "copy!shallow"
     "deep copy"
     "copy!deep"
     "deepcopy function"
     "function!deepcopy"
     "exception!AttributeError"
     "AttributeError"
     "type function"
     "function!type"
     "hasattr function"
     "function!hasattr"
     "attribute"
     "instantiate"
     "Time class"
     "class!Time"
     "prototype and patch"
     "development plan!prototype and patch"
     "pure function"
     "function type!pure"
     "Monty Python and the Holy Grail"
     "modifier"
     "function type!modifier"
     "functional programming style"
     "planned development"
     "development plan!designed"
     "sexagesimal"
     "subtraction with borrowing"
     "invariant"
     "assert statement"
     "statement!assert"
     "designed development"
     "datetime module"
     "module!datetime"
     "birthday"
     "Double Day"
     "object!printing"
     "function syntax"
     "method syntax"
     "subject"
     "self (parameter name)"
     "parameter!self"
     "metaphor, method invocation"
     "positional argument"
     "argument!positional"
     "other (parameter name)"
     "parameter!other"
     "init method"
     "method!init"
     "str method@\\_\\_str\\_\\_ method"
     "method!\\_\\_str\\_\\_"
     "add method"
     "method!add"
     "operator overloading"
     "type-based dispatch"
     "dispatch, type-based"
     "radd method"
     "method!radd"
     "dispatch!type-based"
     "polymorphism"
     "attribute!initializing"
     "dict attribute@\\_\\_dict\\_\\_ attribute"
     "attribute!\\_\\_dict\\_\\_"
     "traversal!dictionary"
     "getattr function"
     "function!getattr"
     "maintainable"
     "object-oriented design"
     "object-oriented language"
     "overloading"
     "operator!overloading"
     "information hiding"
     "default value!avoiding mutable"
     "mutable object, as default value"
     "worst bug"
     "bug!worst"
     "Kangaroo class"
     "class!Kangaroo"
     "deck"
     "card, playing"
     "poker"
     "rank"
     "suit"
     "encode"
     "encrypt"
     "map to"
     "Card class"
     "class!Card"
     "class attribute"
     "attribute!class"
     "cmp method@\\_\\_cmp\\_\\_ method"
     "method!\\_\\_cmp\\_\\_"
     "list!of objects"
     "deck, playing cards"
     "loop!nested"
     "Deck class"
     "class!Deck"
     "accumulator!string"
     "string!accumulator"
     "veneer"
     "shuffle function"
     "function!shuffle"
     "inheritance"
     "parentheses!parent class in"
     "parent class"
     "class!parent"
     "Hand class"
     "class!Hand"
     "child class"
     "class!child"
     "IS-A relationship"
     "HAS-A relationship"
     "class diagram"
     "diagram!class"
     "multiplicity (in class diagram)"
     "mro method"
     "method!mro"
     "method resolution order"
     "Liskov substitution principle"
     "development plan!data encapsulation"
     "data encapsulation"
     "conditional expression"
     "expression!conditional"
     "NaN"
     "factorial"
     "list comprehension"
     "loop variable"
     "generator expression"
     "expression!generator"
     "generator object"
     "object!generator"
     "StopIteration"
     "exception!StopIteration"
     "sum"
     "any"
     "built-in function!any"
     "all"
     "dictionary subtraction"
     "object!set"
     "set subtraction"
     "subset"
     "Counter"
     "object!Counter"
     "multiset"
     "collections"
     "module!collections"
     "defaultdict"
     "object!defaultdict"
     "factory function"
     "setdefault"
     "namedtuple"
     "object!namedtuple"
     "factory"
     "conditional"
     "hanging"
     "loop!condition"
     "dir function"
     "function!dir"
     "debugger (pdb)"
     "pdb (Python debugger)"
     "testing!minimal test case"
     "test case, minimal"
     "model, mental"
     "mental model"
     "expression!big and hairy"
     "big, hairy expression"
     "precedence"
     "frustration"
     "rage"
     "debugging!superstition"
     "superstitious debugging"
     "analysis of algorithms"
     "Obama, Barack"
     "Schmidt, Eric"
     "bubble sort"
     "radix sort"
     "comparing algorithms"
     "machine model"
     "worst case"
     "average case"
     "order of growth"
     "leading term"
     "exponent"
     "leading coefficient"
     "crossover point"
     "big-oh notation"
     "linear growth"
     "quadratic growth"
     "badness"
     "logarithmic growth"
     "exponential growth"
     "analysis of primitives"
     "indexing"
     "string methods"
     "tuple methods"
     "string concatenation"
     "join@{\\tt join}"
     "list methods"
     "sorting"
     "dictionary methods"
     "comparison sort"
     "stable sort"
     "linear search"
     "in@{\\tt in} operator"
     "LinearMap@{\\tt LinearMap}"
     "KeyError@{\\tt KeyError}"
     "red-black tree"
     "BetterMap@{\\tt BetterMap}"
     "bounded"
     "HashMap"
     "rehashing"
     "constant time"
     "average cost"
     "geometric resizing"
     "Big-Oh notation"
     "linear"
     "quadratic")
    (LaTeX-add-environments
     "exercise")
    (LaTeX-add-labels
     "#1"
     "hello"
     "variables"
     "fig.state2"
     "funcchap"
     "functionchap"
     "parameters"
     "stackdiagram"
     "fig.stack"
     "turtlechap"
     "turtle"
     "repetition"
     "refactoring"
     "docstring"
     "fig.flowers"
     "fig.pies"
     "conditional.execution"
     "alternative.execution"
     "recursion"
     "recursive.stack"
     "fig.stack2"
     "whitespace"
     "fig.koch"
     "fruitchap"
     "incremental.development"
     "boolean"
     "more.recursion"
     "fig.stack3"
     "one.more.example"
     "guardian"
     "factdebug"
     "ackermann"
     "palindrome"
     "fig.assign2"
     "update"
     "squareroot"
     "bisectbug"
     "strings"
     "for"
     "slice"
     "fig.banana"
     "find"
     "counter"
     "optional"
     "inboth"
     "fig.state4"
     "isreverse"
     "exrotate"
     "wordplay"
     "wordlist"
     "search"
     "sequence"
     "mutable"
     "fig.liststate"
     "filter"
     "equivalence"
     "fig.list1"
     "fig.list2"
     "fig.list3"
     "list.arguments"
     "fig.stack5"
     "cumulative"
     "anagram"
     "duplicate"
     "wordlist1"
     "bisection"
     "histogram"
     "raise"
     "invert"
     "fig.dict1"
     "memoize"
     "fig.fibonacci"
     "wordlist2"
     "setdefault"
     "exrotatepairs"
     "tuplechap"
     "tuple.assignment"
     "gather"
     "dictuple"
     "fig.tuple1"
     "fig.dict2"
     "anagrams"
     "analysis"
     "dictsub"
     "randomwords"
     "randhist"
     "markov"
     "paths"
     "catch"
     "modules"
     "checksum"
     "clobjects"
     "point"
     "attributes"
     "fig.point"
     "rectangles"
     "fig.rectangle"
     "copying"
     "fig.rectangle2"
     "hasattr"
     "time"
     "isafter"
     "fig.time"
     "increment"
     "prototype"
     "operator.overloading"
     "polymorphism"
     "kangaroo"
     "class.attribute"
     "fig.card1"
     "comparecard"
     "printdeck"
     "class.diagram"
     "fig.class1"
     "poker"
     "sets"
     "algorithms"
     "hashtable"
     "fig.hash")
    (TeX-add-symbols
     '("Anchor" 1)
     "thetitle"
     "theversion"
     "thedate"
     "anchorcnt"
     "mymapsto")
    (TeX-run-style-hooks
     "localdef"
     "kotex"
     "hyperref"
     "bookmarks"
     "appendix"
     "upquote"
     "hevea"
     "setspace"
     "makeidx"
     "exercise"
     "amsthm"
     "amsmath"
     "graphicx"
     "fancyhdr"
     "url"
     "mathpazo"
     "textcomp"
     ""
     "fontenc"
     "T1"
     "geometry"
     "vmarginratio=1:1"
     "hmarginratio=3:2"
     "height=8.5in"
     "width=5.5in"
     "latex2e"
     "bk10"
     "10pt"
     "latexonly")))

